version: '3.8'

services:
  # Сервис базы данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    ports:
      - "8081:8080"
    environment:
      ConnectionStrings__CureTrackerDbContext: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};"
      TelegramBot__Token: ${TELEGRAM_TOKEN}
      JwtOptions__Secret: ${JWT_SECRET} 
      ASPNETCORE_URLS: "http://+:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8081
    depends_on:
      - backend

volumes:
  postgres_data: