services:
  postgres:
    ports:
      - "5432:5432"

  backend:
    ports:
      - "8081:8080"

  frontend:
    build:
      args:
        NEXT_PUBLIC_API_BASE_URL: "http://localhost:8081"
    ports:
      - "3000:3000"


  nginx:
    ports: []

  certbot:
    entrypoint: "echo 'Certbot is disabled in local environment'" 